---
- block:
  - include: system.yml
  - include: repo.yml
  - include: scripts.yml
  - include: initial_dump.yml
    when: "{{ zbackup_do_initial_dump }}"
  when: not zbackup_uninstall

- include: uninstall.yml
  when: zbackup_uninstall
