---
- block:
  - import_tasks: system.yml
  - import_tasks: repo.yml
  - import_tasks: scripts.yml
  - import_tasks: initial_dump.yml
    when: zbackup_do_initial_dump
  when: not zbackup_uninstall

- import_tasks: uninstall.yml
  when: zbackup_uninstall
