---
- name: Ensure that our dump/get scripts are there
  become: true
  template:
    src: "{{ item }}.sh"
    dest: "{{ zbackup_storage_path }}/{{ item }}.sh"
    owner: "{{ zbackup_owner }}"
    mode: u=rwx,g=,o=
  with_items:
    - dump
    - getlatest
