---
- name: Ensure packages needed are present
  apt: "name={{ item }} state=present"
  with_items:
    - zbackup

- name: Ensure that zbackup_owner exists
  user:
    name: "{{ zbackup_owner }}"
    createhome: no

